### ISSUE TITLE
您好能修改一下吗

### ISSUE THREAD

**Issue by rmxf888** [chan2zen/rust-chan#2]
![OY0J8~OOWJL)9~P}5QXCRBK](https://github.com/user-attachments/assets/a023eecd-67e9-400e-b0f1-8c53c5b2352a)
这些高低点能放在当成的k线上面吗，
现在很多这种移到后面k线上面 导致力度计算不准 ，麻烦您 能修改一下吗
谢谢

其它的做的非常好  最好能做个次级别中枢 也就是 顶底分型 连线 来处理画中枢的功能

**Comment by rmxf888** [comment]
还有一点 能不能加个 类二买卖 和 类三买卖  提示     这样这个公式 就非常完美了 谢谢 辛苦了

**Comment by rmxf888** [comment]
通达信有64位了  升级 完成后 能不能生成一个64位的dll  谢谢您

**Comment by chan2zen** [comment]
我没有找到64位下载链接，打包了一个64位的版本，你试一下。
[rust_chan.zip](https://github.com/user-attachments/files/17724569/rust_chan.zip)

**Comment by rmxf888** [comment]
您 好 ，谢谢 64位的 可以绑定了  http://www.70822.com/soft/sort012/sort018/down-175493.html  这里下载的  还在内测  ，你写的这个很好 速度非常快 ，感谢 如果 能把上面那个我说的那两个功能完善一下就太完美了 感谢

**Comment by chan2zen** [comment]
> 您 好 ，谢谢 64位的 可以绑定了 http://www.70822.com/soft/sort012/sort018/down-175493.html 这里下载的 还在内测 ，你写的这个很好 速度非常快 ，感谢 如果 能把上面那个我说的那两个功能完善一下就太完美了 感谢

 第一个功能是有争议的，有人说要放在最高最低点，有人说要放在最后合并的点上，后续考虑做一个开关配置项，目前你可以通过调整通达信公式使用合并后的最高最低点来向前校正位置；

类2、3买也可以通过通达信公式尝试一下，或者有什么好的实现思路也可以提供来交流一下。

**Comment by rmxf888** [comment]
加个开  开关配置项  这样最好了    类2  类3  就是中枢的 完美点  加上会更好一些 。 以后 生成 可以生成两个 一个32位 一个64位 这样通达信 就都 能选择着用了      非常感谢 ！
